/*
 * Copyright (C) 2024 pbellotto (pedro.augusto.bellotto@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Metadata } from "next";
import "./globals.css";
import Navbar from './components/Navbar/Navbar';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Footer from './components/Footer/Footer';

export const viewport = {
    width: 'device-width',
    initialScale: 1
};

export const metadata: Metadata = {
    title: 'Task4ge',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link href="https://fonts.cdnfonts.com/css/selawik" rel="stylesheet" />
            </head>
            <UserProvider>
                <body className='antialiased'>
                    <Navbar />
                    {children}
                    <Footer />
                </body>
            </UserProvider>
        </html>
    );
}
